url: https://wedding.ratanparai.com
baseurl:

# Site settings
title: Ratan & Mili
email: contact@ratanparai.com
description: "Ratan & Mili is getting married"


# Team names, titles and social links
people:
- name: Shathy Raj Shuvo
  pic: 3
  position: Bridegroom's Brother
  social:
    - title: twitter
      url: https://twitter.com/shuvaparai


# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  # - title: twitter
  #   url: http://twitter.com/jekyllrb
  # - title: facebook
  #   url:
  # - title: stack-overflow
  #   url: http://stackoverflow.com/questions/tagged/jekyll
  # - title: bitbucket 
  #   url: http://bitbucket.org/jekyll
  # - title: github
  #   url: http://github.com/jekyll

# Postal address (add as many lines as necessary)
address:
  - line: 3481 Melrose Place
  - line: Beverly Hills, CA 90210

# Build settings
markdown: kramdown
permalink: pretty